name: "SMSAlert Send SMS"
description: "Send an SMS using SMSAlert"
author: "SMSAlert"
branding:
  icon: "smartphone"
  color: "blue"
inputs:
  senderid:
    description: "The senderid to send an SMS from"
    required: true
  recipientNumber:
    description: "The number to send an SMS to"
    required: true
  message:
    description: "The message to send"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
