name: 'cozyvision-smsalert'
author: 'Smsalert'
description: 'Send an SMS from GitHub Actions using SMS Alert'
inputs:
  senderid:
    description: 'senderid in your Smsalert account to send the SMS from'
    required: true
  toPhoneNumber:
    description: 'Phone number to send the SMS to'
    required: true
  message:
    description: 'The message you want to send'
    required: true
outputs:
  messageSid:
    description: 'The Smsalert Message SID'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'red'
  icon: 'message-circle'
